# Config file to find approximated IF using certain approximation method (run_IF_exp.py)
results_dir: "/results/wiki"
hyperparam_search: False
break_early: False # Use if you want to run less than one epoch
task: "wiki"
device: cuda:1
n: 1903 # either "all" = all data or an integer < len(train_data)
n_test: 200 # either "all" = all data or an integer < len(test_data)
approx_method: svrg
tr_bsz: 1
te_bsz: 2
iterations: 5

# Model parameters
dropout: 0.0
model_seed: 0
data_seed: 1


# Method parameters
method:
  lr: 1e-6
  num_epochs: 25
  regularization_param: 1
  loss_at_epoch: True
  conjugate_grad:
    eps: .01
  arnoldi:
    top_k: 10


