# Config file to finetune base model on zsRE or WikiText (run_train_model.py)
results_dir: "/models/wiki"
saved_model_dir: "/models/wiki"
hyperparam_search: False
task: "wiki"
iterations: 50
n: 275 # either "all" = all data or an integer < len(train_data)
n_test: 200 # either "all" = all data or an integer < len(test_data)
batch_size: 4
device: cuda:0

# Model parameters
dropout: 0.0
model_seed: 0
data_seed: 1

ft:
  lr: 1e-5
